-- CREATE HANA TECHNICAL USER
CREATE USER PS_USER PASSWORD Password1;

-- ROLES (SPS09)
GRANT AFL__SYS_AFL_APL_AREA_EXECUTE TO PS_USER;
GRANT AFLPM_CREATOR_ERASER_EXECUTE TO PS_USER;

-- ROLE (SPS10)
CALL GRANT_ACTIVATED_ROLE('sap.pa.apl.base.roles::APL_EXECUTE','PS_USER');

-- IMPORT DEMO SCHEMA PS_DATA

-- READ ACCESS TO DEMO SCHEMA
GRANT SELECT ON SCHEMA PS_DATA TO PS_USER;
